# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "New American Library"), title: "1984", author: "George Orwell", description: "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of negative utopia -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time.", ISBN: "9780451524935", image_url: "https://prodimage.images-bn.com/pimages/9780451524935_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Nonfiction"), publisher: Publisher.find_or_create_by(name: "Simon & Schuster"), title: "Leonardo da Vinci", author: "Walter Isaacson", description: "Based on thousands of pages from Leonardo’s astonishing notebooks and new discoveries about his life and work, Walter Isaacson weaves a narrative that connects his art to his science. He shows how Leonardo’s genius was based on skills we can improve in ourselves, such as passionate curiosity, careful observation, and an imagination so playful that it flirted with fantasy.", ISBN: "9781501139154", image_url: "https://prodimage.images-bn.com/pimages/9781501139154_p0_v4_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "ABRAMS"), title: "The Getaway", subtitle: "Diary of a Wimpy Kid Series #12", author: "Jeff Kinney", description: "Greg Heffley and his family are getting out of town. With the cold weather and the stress of the approaching holiday season, the Heffleys decide to escape to a tropical island resort for some much-needed rest and relaxation. A few days in paradise should do wonders for Greg and his frazzled family. But the Heffleys soon discover that paradise isn't everything it's cracked up to be. Sun poisoning, stomach troubles, and venomous critters all threaten to ruin the family's vacation. Can their trip be saved, or will this island getaway end in disaster?", ISBN: "9781419730603", image_url: "https://prodimage.images-bn.com/pimages/9781419730603_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Young Adult"), publisher: Publisher.find_or_create_by(name: "Penguin Young Readers Group"), title: "Turtles All the Way Down", author: "John Green", description: "Sixteen-year-old Aza never intended to pursue the mystery of fugitive billionaire Russell Pickett, but there’s a hundred thousand dollar reward at stake and her Best and Most Fearless Friend, Daisy, is eager to investigate. So together, they navigate the short distance and broad divides that separate them from Russell Pickett’s son, Davis.", ISBN: "9780525555360", image_url: "https://prodimage.images-bn.com/pimages/9780525555360_p0_v5_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fiction"), publisher: Publisher.find_or_create_by(name: "Penguin Publishing Group"), title: "Little Fires Everywhere", author: "Celeste Ng", description: "In Shaker Heights, a placid, progressive suburb of Cleveland, everything is planned -- from the layout of the winding roads, to the colors of the houses, to the successful lives its residents will go on to lead. And no one embodies this spirit more than Elena Richardson, whose guiding principle is playing by the rules.", ISBN: "Penguin Publishing Group", image_url: "https://prodimage.images-bn.com/pimages/9780735224292_p0_v3_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "The Giving Tree", author: "Shel Silverstein", description: "This is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another's capacity to love in return.", ISBN: "9780060256654", image_url: "https://prodimage.images-bn.com/pimages/9780060256654_p0_v7_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "If You Give a Mouse a Cookie", author: "Laura Numeroff", description: "If a hungry little traveler shows up at your house, you might want to give him a cookie. If you give him a cookie, he's going to ask for a glass of milk. He'll want to look in a mirror to make sure he doesn't have a milk mustache, and then he'll ask for a pair of scissors to give himself a trim....", ISBN: "9780060245863", image_url: "https://prodimage.images-bn.com/pimages/9780060245863_p0_v3_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Science"), publisher: Publisher.find_or_create_by(name: "Norton, W. W. & Company, Inc."), title: "Astrophysics for People in a Hurry", author: "Neil deGrasse Tyson", description: "The #1 New York Times Bestseller: The essential universe, from our most celebrated and beloved astrophysicist.What is the nature of space and time? How do we fit within the universe? How does the universe fit within us? There’s no better guide through these mind-expanding questions than acclaimed astrophysicist and best-selling author Neil deGrasse Tyson.But today, few of us have time to contemplate the cosmos. So Tyson brings the universe down to Earth succinctly and clearly, with sparkling wit, in tasty chapters consumable anytime and anywhere in your busy day.While you wait for your morning coffee to brew, for the bus, the train, or a plane to arrive, Astrophysics for People in a Hurry will reveal just what you need to be fluent and ready for the next cosmic headlines: from the Big Bang to black holes, from quarks to quantum mechanics, and from the search for planets to the search for life in the universe.", ISBN: "9780393609394", image_url: "https://prodimage.images-bn.com/pimages/9780393609394_p0_v4_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Horror"), publisher: Publisher.find_or_create_by(name: "Scribner"), title: "Sleeping Beauties", author: "Stephen King", description: "In a future so real and near it might be now, something happens when women go to sleep: they become shrouded in a cocoon-like gauze. If they are awakened, if the gauze wrapping their bodies is disturbed or violated, the women become feral and spectacularly violent. And while they sleep they go to another place, a better place, where harmony prevails and conflict is rare.", ISBN: "9781501163401", image_url: "https://prodimage.images-bn.com/pimages/9781501163401_p0_v3_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Horror"), publisher: Publisher.find_or_create_by(name: "Scribner"), title: "It", subtitle: "A Novel", author: "Stephen King", description: "Stephen King’s terrifying, classic #1 New York Times bestseller, a landmark in American literature (Chicago Sun-Times)—about seven adults who return to their hometown to confront a nightmare they had first stumbled on as teenagers...an evil without a name: It. Welcome to Derry, Maine. It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real.", ISBN: "9781501142970", image_url: "https://prodimage.images-bn.com/pimages/9781501142970_p0_v3_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Science Fiction"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "Ready Player One", author: "Ernest Cline", description: "In the year 2045, reality is an ugly place. The only time teenage Wade Watts really feels alive is when he's jacked into the virtual utopia known as the OASIS. Wade's devoted his life to studying the puzzles hidden within this world's digital confines—puzzles that are based on their creator's obsession with the pop culture of decades past and that promise massive power and fortune to whoever can unlock them.", ISBN: "9780307887443", image_url: "https://prodimage.images-bn.com/pimages/9780307887443_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Science Fiction"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "The Martian", author: "Andy Weir", description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won't have time to starve to death. The damaged machinery, unforgiving environment, or plain-old human error are much more likely to kill him first.", ISBN: "9780553418026", image_url: "https://prodimage.images-bn.com/pimages/9780553418026_p0_v5_s550x406.jpg")


#Book.create(category: Category.find_or_create_by(name: "Thriller"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "Gone Girl", author: "Gillian Flynn", description: "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick’s clever and beautiful wife disappears. Husband-of-the-Year Nick isn’t doing himself any favors with cringe-worthy daydreams about the slope and shape of his wife’s head, but passages from Amy's diary reveal the alpha-girl perfectionist could have put anyone dangerously on edge. Under mounting pressure from the police and the media—as well as Amy’s fiercely doting parents—the town golden boy parades an endless series of lies, deceits, and inappropriate behavior. Nick is oddly evasive, and he’s definitely bitter—but is he really a killer?", ISBN: "9780307588371", image_url: "https://prodimage.images-bn.com/pimages/9780307588371_p0_v5_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "Blood Meridian, or The Evening Redness in the West", author: "Cormac McCarthy", description: "An epic novel of the violence and depravity that attended America's westward expansion, Blood Meridian brilliantly subverts the conventions of the Western novel and the mythology of the wild west. Based on historical events that took place on the Texas-Mexico border in the 1850s, it traces the fortunes of the Kid, a fourteen-year-old Tennesseean who stumbles into the nightmarish world where Indians are being murdered and the market for their scalps is thriving.", ISBN: "9780679728757", image_url: "https://prodimage.images-bn.com/pimages/9780679728757_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Poetry"), publisher: Publisher.find_or_create_by(name: "Andrews McMeel Publishing"), title: "Milk and Honey", author: "Rupi Kaur", description: "The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. Milk and Honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.", ISBN: "9781449474256", image_url: "https://prodimage.images-bn.com/pimages/9781449474256_p0_v11_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "1Q84", author: "Haruki Murakami", description: "The year is 1984 and the city is Tokyo. A young woman named Aomame follows a taxi driver’s enigmatic suggestion and begins to notice puzzling discrepancies in the world around her. She has entered, she realizes, a parallel existence, which she calls 1Q84 —Q is for question mark. A world that bears a question. Meanwhile, an aspiring writer named Tengo takes on a suspect ghostwriting project. He becomes so wrapped up with the work and its unusual author that, soon, his previously placid life begins to come unraveled.", ISBN: "9780307476463", image_url: "https://prodimage.images-bn.com/pimages/9780307476463_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fiction"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "Colorless Tsukuru Tazaki and His Years of Pilgrimage", author: "Haruki Murakami", description: "Colorless Tsukuru Tazaki and His Years of Pilgrimage is the long-awaited new novel—a book that sold more than a million copies the first week it went on sale in Japan—from the award-winning, internationally best-selling author Haruki Murakami.", ISBN: "9780804170123", image_url: "https://prodimage.images-bn.com/pimages/9780804170123_p0_v3_s550x406.jpg")

#wimpy_kid = Book.find_by(title: "The Getaway")
#wimpy_kid.update_columns(ISBN: "9781419725456")

#little_fires = Book.find_by(title: "Little Fires Everywhere")
#little_fires.update_columns(ISBN: "9780735224292")

#Book.create(category: Category.find_or_create_by(name: "Mystery"), publisher: Publisher.find_or_create_by(name: "Grand Central Publishing"), title: "Blue Labyrinth", subtitle: "Pendergast #14", author: "Douglas Preston, Lincoln Child", description: "A long-buried family secret has come back to haunt Special Agent Aloysius Pendergast. It begins with murder. One of Pendergast's most implacable, most feared enemies is found on his doorstep, dead. Pendergast has no idea who is responsible for the killing, or why the body was brought to his home. The mystery has all the hallmarks of the perfect crime, save for an enigmatic clue: a piece of turquoise lodged in the stomach of the deceased.", ISBN: "9781455525898", image_url: "https://prodimage.images-bn.com/pimages/9781455525911_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "William Morrow"), title: "American Gods", author: "Neil Gaiman", description: "It has been a decade since #1 New York Times bestselling author Neil Gaiman (Sandman, Anansi Boys, The Graveyard Book) rocked the literary world with American Gods—his breathtaking tale of the war on Earth between old gods and new. For those who have yet to experience Gaiman’s bestselling tour de force—a novel USA Today called a powerful, searing force that makes readers confront what is real and what is not'-and for those eager to enter this astonishing world again, comes the Author’s Preferred Text 10th Anniversary Edition. Winner of the Hugo, Nebula, Locus, and Bram Stoker Awards, with a special introduction by the author, this is American Gods as Neil Gaiman always meant it to be.", ISBN: "9780062080233", image_url: "https://prodimage.images-bn.com/pimages/9780062080233_p0_v3_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "HarperTeen"), title: "Red Queen", author: "Victoria Aveyard", description: "Mare Barrow's world is divided by blood—those with common, Red blood serve the Silver-blooded elite, who are gifted with superhuman abilities. Mare is a Red, scraping by as a thief in a poor, rural village, until a twist of fate throws her in front of the Silver court. Before the king, princes, and all the nobles, she discovers she has an ability of her own.", ISBN: "9780062310637", image_url: "https://prodimage.images-bn.com/pimages/9780062310644_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Thomas & Mercer"), title: "Afterlife", author: "Marcus Sakey", description: "The last thing FBI agent Will Brody remembers is the explosion—a thousand shards of glass surfing a lethal shock wave. He wakes without a scratch. The building is in ruins. His team is gone. Outside, Chicago is dark. Cars lie abandoned. No planes cross the sky. He’s relieved to spot other people—until he sees they’re carrying machetes. Welcome to the afterlife.", ISBN: "9781477848401", image_url: "https://prodimage.images-bn.com/pimages/9781477848401_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Random House Publishing Group"), title: "The World of Lore", subtitle: "Monstrous Creatures", author: "Aaron Mahnke", description: "hey live in shadows—deep in the forest, late in the night, in the dark recesses of our minds. They’re spoken of in stories and superstitions, relics of an unenlightened age, old wives’ tales, passed down through generations. Yet no matter how wary and jaded we have become, as individuals or as a society, a part of us remains vulnerable to them: werewolves and wendigos, poltergeists and vampires, angry elves and vengeful spirits.", ISBN: "9781524797966", image_url: "https://prodimage.images-bn.com/pimages/9781524797966_p0_v5_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Flatiron Books"), title: "Twin Peaks", subtitle: "The Final Dossier", author: "Mark Frost", description: "The return of Twin Peaks is one of the most anticipated events in the history of television. The subject of endless speculation, shrouded in mystery, fans will come flocking to see Mark Frost and David Lynch’s inimitable vision once again grace the screen. Featuring all the characters we know and love from the first series, as well as a list of high-powered actors in new roles, the show will be endlessly debated, discussed, and dissected.", ISBN: "9781250163301", image_url: "https://prodimage.images-bn.com/pimages/9781250163301_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Random House Children's Books"), title: "La Belle Sauvage", subtitle: "Book of Dust Series #1", author: "Philip Pullman", description: "Malcolm Polstead is the kind of boy who notices everything but is not much noticed himself. And so perhaps it was inevitable that he would become a spy....", ISBN: "9780375815300", image_url: "https://prodimage.images-bn.com/pimages/9780375815300_p0_v6_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "Strange Weather", subtitle: "Four Short Novels", author: "Joe Hill", description: "A collection of four chilling novels, ingeniously wrought gems of terror from the brilliantly imaginative, #1 New York Times bestselling author of The Fireman, Joe Hill. One of America’s finest horror writers (Time magazine), Joe Hill has been hailed among legendary talents such as Peter Straub, Neil Gaiman, and Jonathan Lethem. In Strange Weather, this compelling chronicler of human nature’s continual war between good and evil, (Providence Journal-Bulletin) who pushes genre conventions to new extremes (New York Times Book Review) deftly expose the darkness that lies just beneath the surface of everyday life.", ISBN: "9780062663115", image_url: "https://prodimage.images-bn.com/pimages/9780062663115_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Disney Press"), title: "The Ship of the Dead", subtitle: "Magnus Chase and the Gods of Asgard Series #3", author: "Rick Riordan", description: "Magnus Chase, a once-homeless teen, is a resident of the Hotel Valhalla and one of Odin's chosen warriors. As the son of Frey, the god of summer, fertility, and health, Magnus isn't naturally inclined to fighting. But he has strong and steadfast friends, including Hearthstone the elf, Blitzen the dwarf, and Samirah the Valkyrie, and together they have achieved brave deeds, such as defeating Fenris Wolf and battling giants for Thor's hammer, Mjolnir. Now Magnus faces his most dangerous trial yet. His cousin, Annabeth, recruits her boyfriend, Percy Jackson, to give Magnus some pointers, but will his training be enough?", ISBN: "9781423160939", image_url: "https://prodimage.images-bn.com/pimages/9781423160939_p0_v6_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Graywolf Press"), title: "Her Body and Other Parties", author: "Carmen Maria Machado", description: "In Her Body and Other Parties, Carmen Maria Machado blithely demolishes the arbitrary borders between psychological realism and science fiction, comedy and horror, fantasy and fabulism. While her work has earned her comparisons to Karen Russell and Kelly Link, she has a voice that is all her own. In this electric and provocative debut, Machado bends genre to shape startling narratives that map the realities of women’s lives and the violence visited upon their bodies.", ISBN: "9781555977887", image_url: "https://prodimage.images-bn.com/pimages/9781555977887_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "Dover Publications"), title: "The Railway Children", author: "E. Nesbit", description: "Three children, forced to alter their comfortable lifestyle when their father is taken away by strangers, move with their mother to a simple cottage near a railway station where their days are filled with excitement and adventure. First published in 1906, this beloved children's classic has charmed generations of readers.", ISBN: "9780486410227", image_url: "https://prodimage.images-bn.com/pimages/9780486410227_p0_v1_s550x406.jpg")


#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "Little, Brown Books for Young Readers"), title: "The Wizards of Once", author: "Cressida Cowell", description: "Once there were Wizards, who were Magic, and Warriors, who were not. But Xar, son of the King of Wizards, can't cast a single spell. And Wish, daughter of the Warrior Queen, has a banned magical object of her own. When they collide in the wildwood, on the trail of a deadly witch, it's the start of a grand adventure that just might change the fabric of their worlds.", ISBN: "9780316508339", image_url: "https://prodimage.images-bn.com/pimages/9780316508339_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "Candlewick Press"), title: "Race to the Bottom of the Sea", author: "Lindsay Eagar", description: "When her parents, the great marine scientists Dr. and Dr. Quail, are killed in a tragic accident, eleven-year-old Fidelia Quail is racked by grief — and guilt. It was a submarine of Fidelia’s invention that her parents were in when they died, and it was she who pressed them to stay out longer when the raging Undertow was looming. But Fidelia is forced out of her mourning when she’s kidnapped by Merrick the Monstrous, a pirate whose list of treasons stretches longer than a ribbon eel. Her task? Use her marine know-how to retrieve his treasure, lost on the ocean floor. But as Fidelia and the pirates close in on the prize, with the navy hot on their heels, she realizes that Merrick doesn’t expect to live long enough to enjoy his loot. Could something other than black-hearted greed be driving him? Will Fidelia be able to master the perils of the ocean without her parents — and piece together the mystery of Merrick the Monstrous before it’s too late?", ISBN: "9780763679231", image_url: "https://prodimage.images-bn.com/pimages/9780763679231_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "First Second"), title: "Pashmina", author: "Nidhi Chanani", description: "Priyanka Das has so many unanswered questions: Why did her mother abandon her home in India years ago? What was it like there? And most importantly, who is her father, and why did her mom leave him behind? But Pri’s mom avoids these questions—the topic of India is permanently closed.", ISBN: "9781626720879", image_url: "https://prodimage.images-bn.com/pimages/9781626720879_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "Scribner"), title: "The Great Gatsby", author: "F. Scott Fitzgerald", description: "The Great Gatsby, F. Scott Fitzgerald’s third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s.", ISBN: "9780743273565", image_url: "https://prodimage.images-bn.com/pimages/9780743273565_p0_v6_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "Houghton Mifflin Harcourt"), title: "The Little Prince", author: "Antoine de Saint-Exupery", description: "Few stories are as widely read and as universally cherished by children and adults alike as The Little Prince. Richard Howard's translation of the beloved classic beautifully reflects Saint-Exupéry's unique and gifted style. Howard, an acclaimed poet and one of the preeminent translators of our time, has excelled in bringing the English text as close as possible to the French, in language, style, and most important, spirit. The artwork in this edition has been restored to match in detail and in color Saint-Exupéry's original artwork. Combining Richard Howard's translation with restored original art, this definitive English-language edition of The Little Prince will capture the hearts of readers of all ages.", ISBN: "9780156012195", image_url: "https://prodimage.images-bn.com/pimages/9780156012195_p0_v9_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "Little, Brown and Company"), title: "The Catcher in the Rye", author: "J. D. Salinger", description: "Ever since it was first published in 1951, this novel has been the coming-of-age story against which all others are judged. Read and cherished by generations, the story of Holden Caulfield is truly one of America's literary treasures.", ISBN: "9780316769174", image_url: "https://prodimage.images-bn.com/pimages/9780316769174_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "Simon & Schuster"), title: "Catch-22", author: "Joseph Heller", description: "Catch-22 is like no other novel we have ever read. It has its own style, its own rationale, its own extraordinary character. It moves back and forth from hilarity to horror. It is outrageously funny and strangely affecting. It is totally original. It is set in the closing months of World War II, in an American bomber squadron on a small island off Italy. Its hero is a bombardier named Yossarian, who is frantic and furious because thousands of people he hasn't even met keep trying to kill him. (He has decided to live forever even if he has to die in the attempt.)", ISBN: "9780684833392", image_url: "https://prodimage.images-bn.com/pimages/9781451626650_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "The Alchemist", author: "Paulo Coelho", description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.", ISBN: "9780061122415", image_url: "https://prodimage.images-bn.com/pimages/9780062315007_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "Simon & Schuster"), title: "Fahrenheit 451", author: "Ray Bradbury", description: "Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden.", ISBN: "9780307347978", image_url: "https://prodimage.images-bn.com/pimages/9781451673319_p0_v7_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "To Kill a Mockingbird", author: "Harper Lee", description: "One of the best-loved stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country. A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice, it views a world of great beauty and savage inequities through the eyes of a young girl, as her father—a crusading local lawyer—risks everything to defend a black man unjustly accused of a terrible crime.", ISBN: "9780061120084", image_url: "https://prodimage.images-bn.com/pimages/9780060935467_p0_v6_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Scholastic, Inc."), title: "The Hunger Games", subtitle: "Hunger Games Series #1", author: "Suzanne Collins", description: "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she is forced to represent her district in the Games. But Katniss has been close to dead before-and survival.", ISBN: "9780439023481", image_url: "https://prodimage.images-bn.com/pimages/9780439023528_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Scholastic, Inc."), title: "Catching Fire", subtitle: "Hunger Games Series #2", author: "Suzanne Collins", description: "Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. Katniss and Peeta should be happy. After all, they have just won for themselves and their families a life of safety and plenty. But there are rumors of rebellion among the subjects, and Katniss and Peeta, to their horror, are the faces of that rebellion. The Capitol is angry. The Capitol wants revenge.", ISBN: "9780439023498", image_url: "https://prodimage.images-bn.com/pimages/9780545586177_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Scholastic, Inc."), title: "Mockingjay", subtitle: "Hunger Games Series #3", author: "Suzanne Collins", description: "Katniss Everdeen, girl on fire, has survived, even though her home has been destroyed. There are rebels. There are new leaders. A revolution is unfolding. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Though she's long been a part of the revolution, Katniss hasn't known it. Now it seems that everyone has had a hand in the carefully laid plans but her.", ISBN: "9780439023511", image_url: "https://prodimage.images-bn.com/pimages/9780545663267_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "Replica", subtitle: "Replica Duology Series #1", author: "Lauren Oliver", description: "From Lauren Oliver, New York Times bestselling author of Before I Fall and the Delirium trilogy, comes an epic, masterful novel that explores issues of individuality, identity, and humanity. Replica is a flip book that contains two narratives in one, and it is the first in a duology. Turn the book one way and read Lyra’s story; turn the book over and upside down and read Gemma’s story. The stories can be read separately, one after the other, or in alternating chapters. The two distinct parts of this astonishing novel combine to produce an unforgettable journey. Even the innovative book jacket mirrors and extends the reading experience.", ISBN: "9780062394163", image_url: "https://prodimage.images-bn.com/pimages/9780062394170_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "Ringer", subtitle: "Replica Duology Series #2", author: "Lauren Oliver", description: "In the world outside of the Haven Institute, Lyra and Caelum are finding it hard to be human—and Lyra, infected at Haven with a terrible disease, finds her symptoms are growing worse. When Caelum leaves without warning, Lyra follows him, seeking a pioneering organization in Philadelphia that might have a cure. But what they uncover there is a shocking connection to their past, even as their future seems in danger of collapsing.", ISBN: "9781473615038", image_url: "https://prodimage.images-bn.com/pimages/9780062394194_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "The Handmaid's Tale", author: "Margaret Atwood", description: "Offred is a Handmaid in the Republic of Gilead. She may leave the home of the Commander and his wife once a day to walk to food markets whose signs are now pictures instead of words because women are no longer allowed to read. She must lie on her back once a month and pray that the Commander makes her pregnant, because in an age of declining births, Offred and the other Handmaids are valued only if their ovaries are viable. Offred can remember the days before, when she lived and made love with her husband Luke; when she played with and protected her daughter; when she had a job, money of her own, and access to knowledge. But all of that is gone now.... Funny, unexpected, horrifying, and altogether convincing, The Handmaid's Tale is at once scathing satire, dire warning, and literary tour de force.", ISBN: "9780385490818", image_url: "https://prodimage.images-bn.com/pimages/9780525435006_p0_v1_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "Brave New World", author: "Aldous Huxley", description: "Aldous Huxley is rightly considered a prophetic genius and one of the most important literary and philosophical voices of the 20th Century, and Brave New World is his masterpiece. From the author of The Doors of Perception, Island, and countless other works of fiction, non-fiction, philosophy, and poetry, comes this powerful work of speculative fiction that has enthralled and terrified readers for generations. Brave New World remains absolutely relevant to this day as both a cautionary dystopian tale in the vein of the George Orwell classic 1984, and as thought-provoking, thoroughly satisfying entertainment.", ISBN: "9780060929879", image_url: "https://prodimage.images-bn.com/pimages/9780060850524_p0_v2_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Houghton Mifflin Harcourt"), title: "The Giver", author: "Lois Lowry", description: "The Giver, the 1994 Newbery Medal winner, has become one of the most influential novels of our time. The haunting story centers on twelve-year-old Jonas, who lives in a seemingly ideal, if colorless, world of conformity and contentment. Not until he is given his life assignment as the Receiver of Memory does he begin to understand the dark, complex secrets behind his fragile community. Lois Lowry has written three companion novels to The Giver, including Gathering Blue, Messenger, and Son.", ISBN: "9780385732550", image_url: "https://prodimage.images-bn.com/pimages/9780544336261_p0_v4_s550x406.jpg")

#Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "The Road", author: "Cormac McCarthy", description: "A father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind. It is cold enough to crack stones, and when the snow falls it is gray. The sky is dark. Their destination is the coast, although they don’t know what, if anything, awaits them there. They have nothing; just a pistol to defend themselves against the lawless bands that stalk the road, the clothes they are wearing, a cart of scavenged food—and each other.", ISBN: "9780307265432", image_url: "https://prodimage.images-bn.com/pimages/9780307265432_p0_v4_s550x406.jpg")
