# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Book.create(category: Category.find_or_create_by(name: "Classics"), publisher: Publisher.find_or_create_by(name: "New American Library"), title: "1984", author: "George Orwell", description: "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of negative utopia -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time.", ISBN: "9780451524935", image_url: "https://prodimage.images-bn.com/pimages/9780451524935_p0_v2_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Nonfiction"), publisher: Publisher.find_or_create_by(name: "Simon & Schuster"), title: "Leonardo da Vinci", author: "Walter Isaacson", description: "Based on thousands of pages from Leonardo’s astonishing notebooks and new discoveries about his life and work, Walter Isaacson weaves a narrative that connects his art to his science. He shows how Leonardo’s genius was based on skills we can improve in ourselves, such as passionate curiosity, careful observation, and an imagination so playful that it flirted with fantasy.", ISBN: "9781501139154", image_url: "https://prodimage.images-bn.com/pimages/9781501139154_p0_v4_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "ABRAMS"), title: "The Getaway", subtitle: "Diary of a Wimpy Kid Series #12", author: "Jeff Kinney", description: "Greg Heffley and his family are getting out of town. With the cold weather and the stress of the approaching holiday season, the Heffleys decide to escape to a tropical island resort for some much-needed rest and relaxation. A few days in paradise should do wonders for Greg and his frazzled family. But the Heffleys soon discover that paradise isn't everything it's cracked up to be. Sun poisoning, stomach troubles, and venomous critters all threaten to ruin the family's vacation. Can their trip be saved, or will this island getaway end in disaster?", ISBN: "9781419730603", image_url: "https://prodimage.images-bn.com/pimages/9781419730603_p0_v2_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Young Adult"), publisher: Publisher.find_or_create_by(name: "Penguin Young Readers Group"), title: "Turtles All the Way Down", author: "John Green", description: "Sixteen-year-old Aza never intended to pursue the mystery of fugitive billionaire Russell Pickett, but there’s a hundred thousand dollar reward at stake and her Best and Most Fearless Friend, Daisy, is eager to investigate. So together, they navigate the short distance and broad divides that separate them from Russell Pickett’s son, Davis.", ISBN: "9780525555360", image_url: "https://prodimage.images-bn.com/pimages/9780525555360_p0_v5_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Fiction"), publisher: Publisher.find_or_create_by(name: "Penguin Publishing Group"), author: "Celeste Ng", description: "In Shaker Heights, a placid, progressive suburb of Cleveland, everything is planned -- from the layout of the winding roads, to the colors of the houses, to the successful lives its residents will go on to lead. And no one embodies this spirit more than Elena Richardson, whose guiding principle is playing by the rules.", ISBN: "Penguin Publishing Group", image_url: "https://prodimage.images-bn.com/pimages/9780735224292_p0_v3_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), author: "Shel Silverstein", description: "This is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another's capacity to love in return.", ISBN: "9780060256654", image_url: "https://prodimage.images-bn.com/pimages/9780060256654_p0_v7_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Children"), publisher: Publisher.find_or_create_by(name: "HarperCollins Publishers"), title: "If You Give a Mouse a Cookie", author: "Laura Numeroff", description: "If a hungry little traveler shows up at your house, you might want to give him a cookie. If you give him a cookie, he's going to ask for a glass of milk. He'll want to look in a mirror to make sure he doesn't have a milk mustache, and then he'll ask for a pair of scissors to give himself a trim....", ISBN: "9780060245863", image_url: "https://prodimage.images-bn.com/pimages/9780060245863_p0_v3_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Science"), publisher: Publisher.find_or_create_by(name: "Norton, W. W. & Company, Inc."), author: "Neil deGrasse Tyson", description: "The #1 New York Times Bestseller: The essential universe, from our most celebrated and beloved astrophysicist.What is the nature of space and time? How do we fit within the universe? How does the universe fit within us? There’s no better guide through these mind-expanding questions than acclaimed astrophysicist and best-selling author Neil deGrasse Tyson.But today, few of us have time to contemplate the cosmos. So Tyson brings the universe down to Earth succinctly and clearly, with sparkling wit, in tasty chapters consumable anytime and anywhere in your busy day.While you wait for your morning coffee to brew, for the bus, the train, or a plane to arrive, Astrophysics for People in a Hurry will reveal just what you need to be fluent and ready for the next cosmic headlines: from the Big Bang to black holes, from quarks to quantum mechanics, and from the search for planets to the search for life in the universe.", ISBN: "9780393609394", image_url: "https://prodimage.images-bn.com/pimages/9780393609394_p0_v4_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Horror"), publisher: Publisher.find_or_create_by(name: "Scribner"), title: "It", subtitle: "The Novel", author: "Stephen King", description: "In a future so real and near it might be now, something happens when women go to sleep: they become shrouded in a cocoon-like gauze. If they are awakened, if the gauze wrapping their bodies is disturbed or violated, the women become feral and spectacularly violent. And while they sleep they go to another place, a better place, where harmony prevails and conflict is rare.", ISBN: "9781501163401", image_url: "https://prodimage.images-bn.com/pimages/9781501163401_p0_v3_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Horror"), publisher: Publisher.find_or_create_by(name: "Scribner"), author: "Stephen King", description: "Stephen King’s terrifying, classic #1 New York Times bestseller, a landmark in American literature (Chicago Sun-Times)—about seven adults who return to their hometown to confront a nightmare they had first stumbled on as teenagers...an evil without a name: It. Welcome to Derry, Maine. It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real.", ISBN: "9781501142970", image_url: "https://prodimage.images-bn.com/pimages/9781501142970_p0_v3_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Science Fiction"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "Ready Player One", author: "Ernest Cline", description: "In the year 2045, reality is an ugly place. The only time teenage Wade Watts really feels alive is when he's jacked into the virtual utopia known as the OASIS. Wade's devoted his life to studying the puzzles hidden within this world's digital confines—puzzles that are based on their creator's obsession with the pop culture of decades past and that promise massive power and fortune to whoever can unlock them.", ISBN: "9780307887443", image_url: "https://prodimage.images-bn.com/pimages/9780307887443_p0_v2_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Science Fiction"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "The Martian", author: "Andy Weir", description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won't have time to starve to death. The damaged machinery, unforgiving environment, or plain-old human error are much more likely to kill him first.", ISBN: "9780553418026", image_url: "https://prodimage.images-bn.com/pimages/9780553418026_p0_v5_s550x406.jpg")


Book.create(category: Category.find_or_create_by(name: "Thriller"), publisher: Publisher.find_or_create_by(name: "Crown/Archetype"), title: "Gone Girl", author: "Gillian Flynn", description: "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick’s clever and beautiful wife disappears. Husband-of-the-Year Nick isn’t doing himself any favors with cringe-worthy daydreams about the slope and shape of his wife’s head, but passages from Amy's diary reveal the alpha-girl perfectionist could have put anyone dangerously on edge. Under mounting pressure from the police and the media—as well as Amy’s fiercely doting parents—the town golden boy parades an endless series of lies, deceits, and inappropriate behavior. Nick is oddly evasive, and he’s definitely bitter—but is he really a killer?", ISBN: "9780307588371", image_url: "https://prodimage.images-bn.com/pimages/9780307588371_p0_v5_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Dystopian"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "Blood Meridian, or The Evening Redness in the West", author: "Cormac McCarthy", description: "An epic novel of the violence and depravity that attended America's westward expansion, Blood Meridian brilliantly subverts the conventions of the Western novel and the mythology of the wild west. Based on historical events that took place on the Texas-Mexico border in the 1850s, it traces the fortunes of the Kid, a fourteen-year-old Tennesseean who stumbles into the nightmarish world where Indians are being murdered and the market for their scalps is thriving.", ISBN: "9780679728757", image_url: "https://prodimage.images-bn.com/pimages/9780679728757_p0_v1_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Poetry"), publisher: Publisher.find_or_create_by(name: "Andrews McMeel Publishing"), title: "Milk and Honey", author: "Rupi Kaur", description: "The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. Milk and Honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.", ISBN: "9781449474256", image_url: "https://prodimage.images-bn.com/pimages/9781449474256_p0_v11_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Fantasy"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "1Q84", author: "Haruki Murakami", description: "The year is 1984 and the city is Tokyo. A young woman named Aomame follows a taxi driver’s enigmatic suggestion and begins to notice puzzling discrepancies in the world around her. She has entered, she realizes, a parallel existence, which she calls 1Q84 —Q is for question mark. A world that bears a question. Meanwhile, an aspiring writer named Tengo takes on a suspect ghostwriting project. He becomes so wrapped up with the work and its unusual author that, soon, his previously placid life begins to come unraveled.", ISBN: "9780307476463", image_url: "https://prodimage.images-bn.com/pimages/9780307476463_p0_v1_s550x406.jpg")

Book.create(category: Category.find_or_create_by(name: "Fiction"), publisher: Publisher.find_or_create_by(name: "Knopf Doubleday Publishing Group"), title: "Colorless Tsukuru Tazaki and His Years of Pilgrimage", author: "Haruki Murakami", description: "Colorless Tsukuru Tazaki and His Years of Pilgrimage is the long-awaited new novel—a book that sold more than a million copies the first week it went on sale in Japan—from the award-winning, internationally best-selling author Haruki Murakami.", ISBN: "9780804170123", image_url: "https://prodimage.images-bn.com/pimages/9780804170123_p0_v3_s550x406.jpg")
